package:
  templates:
    - QuestTracker

objectives:
  loginfirsttime: 'login persistent global events:StartQuestTrackerFolder'
  QuestTracker: 'variable no-chat persistent'
  QuestTracker1: 'variable no-chat persistent'
  QuestTracker2: 'variable no-chat persistent'
  QuestTracker3: 'variable no-chat persistent'
  SideQuestTracker: 'variable no-chat persistent'
  SideQuestTracker1: 'variable no-chat persistent'

events:
  StartQuestTrackerFolder: 'folder RemoveLoginObjective,StartQuestTrackerObjectives,SetTextForTrackers'
  RemoveLoginObjective: 'objective remove loginfirsttime'
  StartQuestTrackerObjectives: 'folder StartTracker,StartTracker1,StartTracker2,StartTracker3,StartSideTracker,StartSideTracker1'
  StartTracker: 'objective add QuestTracker'
  StartTracker1: 'objective add QuestTracker1'
  StartTracker2: 'objective add QuestTracker2'
  StartTracker3: 'objective add QuestTracker3'
  StartSideTracker: 'objective add SideQuestTracker'
  StartSideTracker1: 'objective add SideQuestTracker1'
  SetTextForTrackers: 'folder StartQuestTracker,StartQuestTracker1,StartQuestTracker2,StartQuestTracker3,StartSideQuestTracker,StartSideQuestTracker1'
  StartQuestTracker: 'variable QuestTracker QuestName " "'
  StartQuestTracker1: 'variable QuestTracker1 Objective1 " "'
  StartQuestTracker2: 'variable QuestTracker2 Objective2 " "'
  StartQuestTracker3: 'variable QuestTracker3 Objective3 " "'
  StartSideQuestTracker: 'variable SideQuestTracker QuestName " "'
  StartSideQuestTracker1: 'variable SideQuestTracker1 Objective1 " "'