##############################################################
#                                                            #
#                   Created by AstralSyntax                  #
#               https://github.com/AstralSyntax              #
#                                                            #
##############################################################
package:
  templates:
    - QuestTracker

objectives:
  loginfirsttime: 'login persistent global events:StartQuestTrackerFolder'
  QuestTracker: 'variable no-chat persistent'
  SideQuestTracker: 'variable no-chat persistent'

events:
  StartQuestTrackerFolder: 'folder RemoveLoginObjective,StartQuestTrackerObjectives,SetTextForTrackers'
  RemoveLoginObjective: 'objective remove loginfirsttime'
  StartQuestTrackerObjectives: 'folder StartTracker,StartSideTracker'
  StartTracker: 'objective add QuestTracker'
  StartSideTracker: 'objective add SideQuestTracker'
  SetTextForTrackers: 'folder StartQuestTracker,StartQuestTracker1,StartQuestTracker2,StartQuestTracker3,StartSideQuestTracker,StartSideQuestTracker1'
  StartQuestTracker: 'variable QuestTracker QuestName " "'
  StartQuestTracker1: 'variable QuestTracker Objective1 " "'
  StartQuestTracker2: 'variable QuestTracker Objective2 " "'
  StartQuestTracker3: 'variable QuestTracker Objective3 " "'
  StartSideQuestTracker: 'variable SideQuestTracker QuestName " "'
  StartSideQuestTracker1: 'variable SideQuestTracker Objective1 " "'

########################## Placeholders ##############################
#  %betonquest_QuestTracker:objective.QuestTracker.QuestName%        #
#  %betonquest_QuestTracker:objective.QuestTracker.Objective1%      #
#  %betonquest_QuestTracker:objective.QuestTracker.Objective2%      #
#  %betonquest_QuestTracker:objective.QuestTracker.Objective3%      #
#  %betonquest_QuestTracker:objective.SideQuestTracker.QuestName%    #
#  %betonquest_QuestTracker:objective.SideQuestTracker.Objective1%  #
######################################################################
