##############################################################
#                                                            #
#                   Created by AstralSyntax                  #
#               https://github.com/AstralSyntax              #
#                                                            #
##############################################################
variables:
### Quest Info - Leave blank, edit this in your package.yml ###
  mainQuestName: ""
  mainQuestObj1: ""
  mainQuestObj2: ""
  mainQuestObj3: ""
  sideQuestName: ""
  sideQuestObj1: ""
  questerName: ""
### Base Reward - You can use this for increasing reward payouts based on level - You can change these ###
  moneyPrefix: '$' # Your economy prefix
  baseReward: 100 # Base reward of 100$
  increaseRate: 1.25 # Base increase of 1.25 (base*increase - 100*1.25*playerLevel)
  rewardPlaceholder: '$moneyPrefix$%math.calc:$baseReward$*$increaseRate$*{ph.player_level}/5~0%' # The math to get the amount of money to pay, dont edit unless you know what you are doing
### Base Block Amount - You can use this for increasing block amount selectors for BREAK?PLACE block events based on level ie: Mining Ores, Chopping Trees ect - You can change these ###
  baseBlocks: 10 # Base amount of blocks to select
  increaseBlockRate: 1.125 # Base increase of 1.125 (base*increase - 10*1.125*playerLevel/5) Negative numbers = Break Block Event, Positive numbers = Place Block Event
  blockPlaceholder: '%math.calc:$increaseBlockRate$*$baseBlocks$*{ph.player_level}/5~0%' # The math to get the amount of blocks, dont edit unless you know what you are doing
### Base Mobe Amount - You can use this for increasing block amount selectors for BREAK?PLACE block events based on level ie: Mining Ores, Chopping Trees ect - You can change these ###
  baseMobs: 2 # Base amount of blocks to select
  increaseMobRate: 1.15 # Base increase of 1.125 (base*increase - 10*1.125*playerLevel/5) Negative numbers = Break Block Event, Positive numbers = Place Block Event
  mobPlaceholder: '%math.calc:$increaseBlockRate$*$baseBlocks$*{ph.player_level}/5~0%' # The math to get the amount of blocks, dont edit unless you know what you are doing
### Repeating Quest - You can change these ###
  cooldownTimer: 1440 # Time till player can re accept a daily quest or similar, time is in minutes 1440 = 24 hours

events:
  setMainQuestName: 'variable QuestTracker.QuestTracker QuestName "$mainQuestName$"'
  setMainQuestObj1: 'variable QuestTracker.QuestTracker1 Objective1 "$mainQuestObj1$"'
  setMainQuestObj2: 'variable QuestTracker.QuestTracker2 Objective2 "$mainQuestObj2$"'
  setMainQuestObj3: 'variable QuestTracker.QuestTracker3 Objective3 "$mainQuestObj3$"'
  setSideQuestName: 'variable QuestTracker.SideQuestTracker QuestName "$sideQuestName$"'
  setSideQuestObj1: 'variable QuestTracker.SideQuestTracker1 Objective1 "$sideQuestObj1$"'