#Made by Fred Reworked by BuzzLiteyear
npcs:
  '0': "Bard"

conditions:
  HasMoney: "money 10"

events:
  TakeMoney: "command money take %player% 10"
  DeleteRegion: "command oa region delete tavern"
  Play_TavernAmbience: "command oa region create tavern https://audio.jukehost.co.uk/0Zf5pup7nkjLW9gMtq11eOmuHFTTO9oo"
  Play_Song1: "command oa region create tavern https://audio.jukehost.co.uk/nt4JPIDOwtYcIcC62fActQkE4Um4PVik" 
  Play_Song2: "command oa region create tavern https://audio.jukehost.co.uk/CsgrsH7Nmfon4OmQrBeLngolNrp8OOzH"
  Play_Song3: "command oa region create tavern https://audio.jukehost.co.uk/0ArkZp5myZqUHBjM4vwRZTB4ZwS4ALyu"
  Play_Song4: "command oa region create tavern https://audio.jukehost.co.uk/egJmmpffCcVgPCGUxUDumCDkSlvWBVC8"
  Play_Song5: "command oa region create tavern https://audio.jukehost.co.uk/7VMVzA6XwUCueiQQrA5XoFAdCEpQTvRV"
  Play_Song6: "command oa region create tavern https://audio.jukehost.co.uk/MJId1o8eTs4LwBKVuvsgehdbFKKNkRup"
  Play_Song7: "command oa region create tavern https://audio.jukehost.co.uk/rFbO3thlkobgL1vuX9SerMyO7REtaUEI"
  Play_Song8: "command oa region create tavern https://audio.jukehost.co.uk/psubSGzUlZrK3UsmrIAMKw0hhjL8ET2H"
  Play_Song9: "command oa region create tavern https://audio.jukehost.co.uk/nYgcXWmCb61oEediMGmKb4Xrl402uVqU"
  Play_Song10: "command oa region create tavern https://audio.jukehost.co.uk/V7ft93MuwyQVcGiI44KbfulAb18AC6Su"

conversations:
  Bard:
    quester: "Bard"
    first: "NPCR1, NoMoney"
    NPC_options:
      NPCR1:
        text: "Hey there! I'm the local Bard! Would you like to make a song request?"
        pointer: "PR1,TavernAmbience,StopMusic,Exit"
        conditions: "HasMoney"
      NoMoney:
        text: "I'm sorry, but it looks like you dont have enough money to choose a song! You can play the default free tavern sound, or come back later!"
        condition: "!HasMoney"
        pointer: "TavernAmbience,Exit"
      NPCR2:
        text: "Great, you can choose one of the songs below for me to play!"
        pointer: "TavernAmbience,Song1,Song2,Song3,Song4,Song5,Song6,Song7,Song8,Song9,Song10,Exit"
    player_options:
      PR1:
        text: "Sure!"
        pointer: "NPCR2"
      Exit:
        text: "Exit."
      TavernAmbience:
        text: "Play Tavern Ambience Noise - Free (1 hour)"
        event: "DeleteRegion, Play_TavernAmbience"
      StopMusic:
        text: "Stop music."
        event: "DeleteRegion"
      Song1:
        text: "Default Tavern Music (1:20 hours)"
        event: "TakeMoney,DeleteRegion,Play_Song1"
      Song2:
        text: "Wild Boar Inn (3:45 min)"
        event: "TakeMoney,DeleteRegion,Play_Song2"
      Song3:
        text: "Out Of The Cold - Skyrim (2:24 min)"
        event: "TakeMoney,DeleteRegion,Play_Song3"
      Song4:
        text: "Fall Of The Magister - Dragon Age (2:55 min)"
        event: "TakeMoney,DeleteRegion,Play_Song4"
      Song5:
        text: "Around The Fire - Skyrim (3:05 min)"
        event: "TakeMoney,DeleteRegion,Play_Song5"
      Song6:
        text: "The Bear And The Maiden Fair - GoT (1:42 min"
        event: "TakeMoney,DeleteRegion,Play_Song6"
      Song7:
        text: "Thunderbrew - World of Warcraft (1:59 min)"
        event: "TakeMoney,DeleteRegion,Play_Song7"
      Song8:
        text: "The Dragonborn Comes - Skyrim (2:57 min)"
        event: "TakeMoney,DeleteRegion,Play_Song8"
      Song9:
        text: "Enchanters - Dragon Age (3:20 min)"
        event: "TakeMoney,DeleteRegion,Play_Song9"
      Song10:
        text: "Toss A Coin To Your Witcher (2:58 min)"
        event: "TakeMoney,DeleteRegion,Play_Song10"